
state [ 
	'name' : 'Alabama' : {'Region' : 'Southeast', 'GDP ': '$7.4 billion', 'Main industry ' : 'item'}, 
	'name' : 'Alaska' : {'Region' : 'Far West', 'GDP ': '$8.7 billion', 'Main industry ' : 'item'}, 
	'name' : 'Arizona' : {'Region' : 'Southwest', 'GDP ': '$11.8 billion', 'Main industry ' : 'item'}, 
	'name' : 'Arkansas' : {'Region' : 'Southeast', 'GDP ': '$6.9 billion', 'Main industry ' : 'item'}, 
	'name' : 'California' : {'Region' : 'Far West', 'GDP ': '$74.4 billion', 'Main industry ' : 'Computer and electronic products manufacturing'}, 
	'name' : 'Colorado' : {'Region' : 'Rocky Mountain', 'GDP ': '$13.8 billion', 'Main industry ' : 'item'}, 
	'name' : 'Connecticut' : {'Region' : 'New England', 'GDP ': '$17.3 billion', 'Main industry ' : 'item'}, 
	'name' : 'Delaware' : {'Region' : 'Mideast', 'GDP ': '$7.9 billion', 'Main industry ' : 'Federal Reserve banks, credit intermediation, and related services'}, 
	'name' : 'Florida' : {'Region' : 'Southeast', 'GDP ': '$35.5 billion', 'Main industry ' : 'item'}, 
	'name' : 'Georgia' : {'Region' : 'Southeast', 'GDP ': '$18.4 billion', 'Main industry ' : 'Federal Reserve banks, credit intermediation, and related services'}, 
	'name' : 'Hawaii' : {'Region' : 'Far West', 'GDP ': '$3.8 billion', 'Main industry ' : 'item'}, 
	'name' : 'Idaho' : {'Region' : 'Rocky Mountain', 'GDP ': '$3.1 billion', 'Main industry ' : 'item'}, 
	'name' : 'Illinois' : {'Region' : 'Great Lakes', 'GDP ': '$25.9 billion', 'Main industry ' : 'item'}, 
	'name' : 'Indiana' : {'Region' : 'Great Lakes', 'GDP ': '$23.8 billion', 'Main industry ' : 'item'}, 
	'name' : 'Iowa' : {'Region' : 'Plains', 'GDP ': '$11.0 billion', 'Main industry ' : 'item'}, 
	'name' : 'Kansas' : {'Region' : 'Plains', 'GDP ': '$4.6 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Kentucky' : {'Region' : 'Southeast', 'GDP ': '$7.9 billion', 'Main industry ' : 'item'}, 
	'name' : 'Louisiana' : {'Region' : 'Southeast', 'GDP ': '$15.4 billion', 'Main industry ' : 'item'}, 
	'name' : 'Maine' : {'Region' : 'New England', 'GDP ': '$3.3 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Maryland' : {'Region' : 'Mideast', 'GDP ': '$11.2 billion', 'Main industry ' : 'item'}, 
	'name' : 'Massachusetts' : {'Region' : 'New England', 'GDP ': '$19.4 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Michigan' : {'Region' : 'Great Lakes', 'GDP ': '$42.4 billion', 'Main industry ' : 'item'}, 
	'name' : 'Minnesota' : {'Region' : 'Plains', 'GDP ': '$11.8 billion', 'Main industry ' : 'item'}, 
	'name' : 'Mississippi' : {'Region' : 'Southeast', 'GDP ': '$3.9 billion', 'Main industry ' : 'item'}, 
	'name' : 'Missouri' : {'Region' : 'Plains', 'GDP ': '$10.9 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Montana' : {'Region' : 'Rocky Mountain', 'GDP ': '$1.9 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Nebraska' : {'Region' : 'Plains', 'GDP ': '$5.5 billion', 'Main industry ' : 'item'}, 
	'name' : 'Nevada' : {'Region' : 'Far West', 'GDP ': '$13.0 billion', 'Main industry ' : 'Tourism and Acommodation'}, 
	'name' : 'New Hampshire' : {'Region' : 'New England', 'GDP ': '$2.9 billion', 'Main industry ' : 'item'}, 
	'name' : 'New Jersey' : {'Region' : 'Mideast', 'GDP ': '$19 billion', 'Main industry ' : 'item'}, 
	'name' : 'New Mexico' : {'Region' : 'Southwest', 'GDP ': '$3.7 billion', 'Main industry ' : 'Oil and gas extraction'}, 
	'name' : 'New York' : {'Region' : 'Mideast', 'GDP ': '$99.1 billion', 'Main industry ' : 'Federal Reserve banks, credit intermediation, and related services'}, 
	'name' : 'North Carolina' : {'Region' : 'Southeast', 'GDP ': '$26.4 billion', 'Main industry ' : 'Federal Reserve banks, credit intermediation, and related services'}, 
	'name' : 'North Dakota' : {'Region' : 'Plains', 'GDP ': '$3.5 billion', 'Main industry ' : 'Mining'}, 
	'name' : 'Ohio' : {'Region' : 'Great Lakes', 'GDP ': '$22.3 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Oklahoma' : {'Region' : 'Southwest', 'GDP ': '$13.7 billion', 'Main industry ' : 'item'}, 
	'name' : 'Oregon' : {'Region' : 'Far West', 'GDP ': '$41.3 billion', 'Main industry ' : 'Computer and electronic products manufacturing'}, 
	'name' : 'Pennsylvania' : {'Region' : 'Mideast', 'GDP ': '$28.0 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Rhode Island' : {'Region' : 'New England', 'GDP ': '$2.8 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'South Carolina' : {'Region' : 'Southeast', 'GDP ': '$6.5 billion', 'Main industry ' : 'Administrative and support services'}, 
	'name' : 'South Dakota' : {'Region' : 'Plains', 'GDP ': '$5.0 billion', 'Main industry ' : 'Federal Reserve banks, credit intermediation, and related services'}, 
	'name' : 'Tennessee' : {'Region' : 'Southeast', 'GDP ': '$13.1 billion', 'Main industry ' : 'item'}, 
	'name' : 'Texas' : {'Region' : 'Southwest', 'GDP ': '$123.9 billion', 'Main industry ' : 'Oil and gas extraction'}, 
	'name' : 'Utah' : {'Region' : 'Rocky Mountain', 'GDP ': '$6.8 billion', 'Main industry ' : 'Federal Reserve banks, credit intermediation, and related services'}, 
	'name' : 'Vermont' : {'Region' : 'New England', 'GDP ': '$1.2 billion', 'Main industry ' : 'Hospitals, Nursing and Residential care facilities'}, 
	'name' : 'Virginia' : {'Region' : 'Southeast', 'GDP ': '$15.7 billion', 'Main industry ' : 'Food, beverage and tobacco products manufacturing'}, 
	'name' : 'Washington' : {'Region' : 'Far West', 'GDP ': '$30.2 billion', 'Main industry ' : 'item'}, 
	'name' : 'West Virginia' : {'Region' : 'Southeast', 'GDP ': '$6.0 billion', 'Main industry ' : 'Mining'}, 
	'name' : 'Wisconsin' : {'Region' : 'Great Lakes', 'GDP ': '$12.2 billion', 'Main industry ' : 'item'}, 
	'name' : 'Wyoming' : {'Region' : 'Rocky Mountain', 'GDP ': '$4.9 billion', 'Main industry ' : 'Mining'}, 
]