
state [ 
	'name' : 'Alabama' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Alaska' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Arizona' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Arkansas' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'California' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Colorado' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Connecticut' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Delaware' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Florida' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Georgia' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Hawaii' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Idaho' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Illinois' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Indiana' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Iowa' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Kansas' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Kentucky' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Louisiana' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Maine' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Maryland' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Massachusetts' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Michigan' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Minnesota' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Mississippi' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Missouri' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Montana' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Nebraska' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Nevada' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'New Hampshire' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'New Jersey' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'New Mexico' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'New York' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'North Carolina' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'North Dakota' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Ohio' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Oklahoma' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Oregon' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Pennsylvania' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Rhode Island' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'South Carolina' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'South Dakota' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Tennessee' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Texas' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Utah' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Vermont' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Virginia' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Washington' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'West Virginia' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Wisconsin' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
	'name' : 'Wyoming' : {'Region' : 'usregionset_complete', 'GDP ': '$xx billion', 'Main Export ' : 'item'}, 
]